"""Auto-generated model profiles.

DO NOT EDIT THIS FILE MANUALLY.
This file is generated by the langchain-profiles CLI tool.

It contains data derived from the models.dev project.

Source: https://github.com/sst/models.dev
License: MIT License

To update these data, refer to the instructions here:

https://docs.langchain.com/oss/python/langchain/models#updating-or-overwriting-profile-data

中文翻译:
自动生成的模型配置文件。
请勿手动编辑此文件。
该文件由 langchain-profiles CLI 工具生成。
它包含源自 models.dev 项目的数据。
来源：https://github.com/sst/models.dev
许可证：麻省理工学院许可证
要更新这些数据，请参阅此处的说明：
https://docs.langchain.com/oss/python/langchain/models#updating-or-overwriting-profile-data
"""

from typing import Any

_PROFILES: dict[str, dict[str, Any]] = {
    "deepseek-chat": {
        "max_input_tokens": 128000,
        "max_output_tokens": 8192,
        "image_inputs": False,
        "audio_inputs": False,
        "video_inputs": False,
        "image_outputs": False,
        "audio_outputs": False,
        "video_outputs": False,
        "reasoning_output": False,
        "tool_calling": True,
    },
    "deepseek-reasoner": {
        "max_input_tokens": 128000,
        "max_output_tokens": 128000,
        "image_inputs": False,
        "audio_inputs": False,
        "video_inputs": False,
        "image_outputs": False,
        "audio_outputs": False,
        "video_outputs": False,
        "reasoning_output": True,
        "tool_calling": True,
    },
}
